services:
  - type: web
    name: stendroid-server
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stendroid-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://stendroid-client.onrender.com
      - key: NODE_ENV
        value: production
      - key: ADMIN_SECRET_KEY
        generateValue: true

  - type: web
    name: stendroid-client
    env: node
    plan: starter
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://stendroid-server.onrender.com

databases:
  - name: stendroid-db
    plan: starter 