services:
  - type: web
    name: linkedin-clone-api
    env: node
    plan: free
    buildCommand: cd server && npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true 